### ISSUE TITLE
`create_alias` is called incorrectly

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog-ruby#13]
This came from a client: ticket [here](https://posthoghelp.zendesk.com/agent/tickets/39)

We set distinct_id for `create_alias` events as explicitly as `nil` in our code, but we should set it to the (previous) distinct_id as e.g. in the python library: https://github.com/PostHog/posthog-python/blob/9d2fa72753ae9e5f4c8095f56f647205c5dac4f7/posthog/client.py#L203-L218

**Comment by AxelTheGerman** [comment]
Thanks for getting that fix out so quickly!
