### ISSUE TITLE
Gem version limitation on "concurrent-ruby"

### ISSUE THREAD

**Issue by jordan-brough** [PostHog/posthog-ruby#24]
PR https://github.com/PostHog/posthog-ruby/pull/19 added a minor-version constraint to concurrent-ruby, without any explanation that I can see:

https://github.com/PostHog/posthog-ruby/pull/19/files#diff-ed813f6c69cb6085908b418178cfcc6a65bc126ca0b613e73116ce7be2675c0a

```diff
-  spec.add_dependency 'concurrent-ruby'
+  spec.add_dependency "concurrent-ruby", "~> 1", "< 1.1.10"
```

Is the `< 1.1.10` intentional and needed?

**Comment by neilkakkar** [comment]
There _was_ some warning spew in 1.1.10 around some deprecation that I don't remember anymore (should've commented this!)

Will re-check if it's still there, and remove the limitation if not, thanks for raising!

**Comment by milani** [comment]
I don't know how to check for those warnings, but I didn't see anything when running tests.

**Comment by liyiy** [comment]
Version 2.2.0 updated to remove this limitation! https://rubygems.org/gems/posthog-ruby/versions/2.2.0

**Comment by liyiy** [comment]
Leaving it open for now for visibility in case others bump into this issue too.

**Comment by milani** [comment]
Thanks @liyiy!
