### ISSUE TITLE
add the function of get distinct id

### ISSUE THREAD

**Issue by shinyo17** [PostHog/posthog-ruby#3]
Hi!
I want to know user's distinct_id.
When I use javascript, I can know user's distinct_id by get_distinct_id().
But In ruby, I heard that there are not function that performs like get_distinct_id in javascript.
Can you create this function in ruby gem?

**Comment by yakkomajuri** [comment]
Hey! We can't really do this in Ruby in a general way because it's meant for use in servers that process requests from an infinite number of users. This is doable on the frontend because client-side we only ever need to deal with only one user.
