### ISSUE TITLE
Stale feature flag evaluations when using with sneakers

### ISSUE THREAD

**Issue by raymzag** [PostHog/posthog-ruby#31]
### Description

Initially posted in [slack](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1681693406511239).

Feature flag local evaluations are stale when called from [sneaker worker](https://github.com/jondot/sneakers). I have a quick demo with sinatra (my main project uses ruby on rails) that I can share. from the logs, I can see the `Loaded # flags`, but calling `$posthog.get_feature_flag` keeps returning stale values instead of the new value from dashboard.

### Replicate

1. Clone https://github.com/raymzag/ruby-sinatra-docker-container
2. Update posthog keys in `docker-compose.yaml`
3. `docker-compose up --build` to build the image
4. `docker-compose up -d` to start the services in the background. 
5. `docker exec -it app /bin/bash` to ssh into the app container. and run `ruby test_worker.rb` (If there is connection errors, give it a min for rabbit-mq to fully start up). This will trigger a local flag evaluation in the sneaker worker.
6. `docker logs -f -n 30 app` to monitor the flag value.
7. Update the feature flag in posthog dashboard, and repeat step 5. The flag's value will still show the old value.

**Comment by raymzag** [comment]
Thanks @neilkakkar for the quick response. That's how I was testing actually and the setup in my demo. 

In here, `web` process returns the new flag value (true), but the `worker` process returns the old value `false`.

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/6531879/232494641-2792c38e-595b-423c-9515-daf4b615b960.png">

**Comment by neilkakkar** [comment]
huh. Can I also see the flag definition?

**Comment by neilkakkar** [comment]
Hmm, sounds like I'll have to set it up myself, nothing obvious seems wrong, except maybe something related to this: https://github.com/PostHog/posthog-ruby/issues/10 where it isn't actually loading the new flags.

Give me a while to set this up

**Comment by raymzag** [comment]
Thanks @neilkakkar for the help. 🙏 I am still trying to figure out as well. Unfortunately, this is blocking issue in our posthog implementation. 🙁

**Comment by raymzag** [comment]
This seems to be working btw. 

```ruby
class MyWorker
  include Sneakers::Worker
  attr_reader :posthog

  def initialize(...)
    super(...)
    @posthog = PostHog::Client.new({
                                    api_key: ENV['POSTHOG_API_KEY'],
                                    personal_api_key: ENV['POSTHOG_PERSONAL_KEY'],
                                    host: ENV['POSTHOG_HOST'],
                                    feature_flags_polling_interval: 10,
                                    on_error: Proc.new { |status, msg| print msg }
                                  })
  end

  from_queue 'myworker'

  def work(data)
    puts "executing at #{Time.now}"
    puts @posthog.get_feature_flag('test-feature', 1)
    ack!
  end
end
```
